import type { Metadata } from 'next'
import { montserrat, lora, firaCode } from '@/styles/fonts'
import './globals.css'

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
}

export default function RootLayout({
  children
}: {
  children: React.ReactNode
}) {
  return (
    <html
      className={`${montserrat.variable} ${lora.variable} ${firaCode.variable}`}
      lang="en"
    >
      <body>{children}</body>
    </html>
  )
}
