export const tokens = {
  duration: {
    immediate: "100ms",
    natural: "250ms",
    slow: "500ms",
    deliberate: "750ms",
  },
  font: {
    family: {
      heading: "Montserrat, sans-serif",
      body: "Lora, serif",
      code: "Fira Code, monospace",
    },
    size: {
      tiny: "0.75rem",
      small: "0.875rem",
      base: "1rem",
      xxs: "1.125rem",
      xs: "1.25rem",
      s: "1.5rem",
      m: "2rem",
      l: "2.5rem",
      xl: "3rem",
      xxl: "4rem",
    },
    height: {
      tiny: "1rem",
      small: "1.25rem",
      base: "1.5rem",
      xxs: "1.75rem",
      xs: "1.75rem",
      s: "2rem",
      m: "2.5rem",
      l: "3.5rem",
      xl: "4rem",
      xxl: "5rem",
    },
    spacing: {
      packed: "-0.05em",
      narrow: "-0.025em",
      wide: "0.1em",
    },
    weight: {
      regular: "400",
      medium: "500",
    },
  },
  screen: {
    large: "1920px",
    desktop: "1280px",
    tablet: "768px",
    mobile: "480px",
    tiny: "321px",
  },
  gradient: {
    rainbow: `linear-gradient(
      45deg,
      #ff0000,
      #ff7300,
      #fffb00,
      #48ff00,
      #00ffd5,
      #002bff,
      #7a00ff,
      #ff00c8,
      #ff0000
    )`,
  },
  space: {
    xxs: "0.125rem",
    xs: "0.5rem",
    s: "1rem",
    m: "2rem",
    l: "4rem",
    xl: "6.5rem",
    xxl: "10.5rem",
    xxxl: "17rem",
  },
}
