import type { Metadata } from 'next'
import { Locale, i18n } from '@/i18n.config'
import { localizePath, setInitialTheme } from '@/lib'
import { getDictionary } from '@/lib/dictionaries'
import { montserrat, lora, firaCode } from '@/theme/fonts'
import { Container } from '@/styled-system/jsx'
import {
  ButtonLink,
  LanguageSwitch,
  Logo,
  Nav,
  ThemeSwitch
} from '@/components'
import './globals.css'

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
}

export async function generateStaticParams() {
  return i18n.locales.map((locale) => ({ lang: locale }))
}

export default async function RootLayout({
  children,
  params
}: {
  children: React.ReactNode
  params: { lang: Locale }
}) {
  const { lang } = params
  const { component } = await getDictionary(lang)

  return (
    <html
      suppressHydrationWarning
      className={`${montserrat.variable} ${lora.variable} ${firaCode.variable}`}
      lang={lang}
    >
      <body>
        <script
          key="set-initial-theme"
          dangerouslySetInnerHTML={{
            __html: setInitialTheme
          }}
        ></script>
        <Container minWidth="100vw" backgroundColor="gray.900">
          <Container
            maxWidth="breakpoint-xl"
            paddingX={{
              base: 'm',
              sm: 'l',
              xl: 'xl',
              '2xl': '0'
            }}
          >
            <Nav>
              <Logo lang={lang}>{component.logo.text}</Logo>
              <ThemeSwitch
                ariaLabel={component.themeSwitch.ariaLabel}
              ></ThemeSwitch>
            </Nav>
            <Nav>
              <ButtonLink style="nav" href={localizePath(lang, '/portfolio/')}>
                Portfolio
              </ButtonLink>
              <ButtonLink style="nav" href={localizePath(lang, '/about/')}>
                About
              </ButtonLink>
              <ButtonLink style="nav" href={localizePath(lang, '/blog/')}>
                Blog
              </ButtonLink>
              <ButtonLink style="outline" href={localizePath(lang, '#contact')}>
                Contact
              </ButtonLink>
            </Nav>
            <main>{children}</main>
            <LanguageSwitch lang={lang}></LanguageSwitch>
          </Container>
        </Container>
      </body>
    </html>
  )
}
