import type { Metadata } from 'next'
import { montserrat, lora, firaCode } from '@/theme/fonts'
import { Locale, i18n } from '@/i18n.config'
import './globals.css'

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
}

export async function generateStaticParams() {
  return i18n.locales.map((locale) => ({ lang: locale }))
}

export default function RootLayout({
  children,
  params
}: {
  children: React.ReactNode
  params: { lang: Locale }
}) {
  return (
    <html
      className={`${montserrat.variable} ${lora.variable} ${firaCode.variable}`}
      lang={params.lang}
    >
      <body>{children}</body>
    </html>
  )
}
